
language: android
jdk: oraclejdk8
env:
  global:
    - secure: "JRdR/atRNz/Cbc0XKvSRHCCNJuzA3MhL3phJgizq1h2VKTxEhhiTrSVHz5OOPwHQXn46Pq4HwrnTBd1GKrnqn6u5ir4h65pgwQXBKXNxHSbDbGKfio3vGoIrB568dNW+FhIMv0+ArLIzfw7qgcVasuNmNbbl9YF7kgLJXmtHkzG7WD94CraEBn9ph949L4oMtG4t8tAec4qpKjIBwjQHzl0E6ccl4RYGoHVDG2jefFOPo73ASyVVZXDE+gMQ2WWaYRY48K7FUc6NcMtQYOHipp6uXopjU9HnUFEQzHls1PENEvfLgYGu9e7WQecV7YuE8Y3YKc5E1WIM17a+1/2wHZNtupSqVY9So82MMcuQKAHMz4Yr/W1zZQ0vvWm+I9oIqwgu14UKwxC8KOUZHgkdo4MPc/J6ff5KZd1wA1JLam5ln7yF2OcQHCkilsN21eMq/eYp49L8nJku02O+mkOdtudcHliDDoEgbt4eotMu7AI66ZJy5gyqYkwlEmYYO6KPS0lK5bhoqe2/4K1Bbw6dZq58LxRzlMvRyh6HEN0epjaQUATEEPD0r5TcvgXDp7CiGgHfYOydw2E+px29w/EzIZ5IxvWd2qHXqldFb/KMC7oLmCA2SZ/EjxM6K1dkYWI7wdjS1wurosDAA0HZDBNFNTnjT3Q9EtEKoS1NMvHgZQo="
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3
    - build-tools-28.0.3
    # The SDK version used to compile your project
    - android-26

  licenses:
    - 'android-sdk-license-.+'

before_script:
    - chmod +x gradlew

jobs:
    include:
        # Put your unit tests here 
        - stage: Unit tests
          name: Release 1
          script: 
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/fontStyleTest
        #The order is ok from https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages, first is script then name
        #Uncomment below when unit tests are ready to integrate to travis
        #  script:
        #Put unit tests for release 2 here, follow the format from release 1.
        #  name: Release 2
        #  script: 
        #Release 3 unit tests
        #  name: Release 3
        #Put your UI tests here
        - stage: UI tests
          name: Release 1
          script: 
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/espresso/fontStyle
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/espresso/themeTest
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/espresso/discoveryPage
        - stage: Code Coverage
          script:
            - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
            - emulator -avd test -no-skin -no-audio -no-window &
            - android-wait-for-emulator
            - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
            - ./graldew createFreeDebugAndroidTest
        #The order is ok from https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages, first is script then name
        #Uncomment below when UI tests are ready to integrate to travis
        #  script:
        #Put your UI tests for release 2 here, follor the format from release 1.
        #  name: Release 2
        #  script:
        #  #Release 3 UI tests
        #  name: Release 3
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r app/build/reports/coverage/free/debug/report.xml
