language: android
android:
  components:
    - build-tools-28.0.1
    - android-23
    - android-28
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
