language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-26

  licenses:
    - 'android-sdk-license-.+'

before_script:
    - chmod +x gradlew

jobs:
    include:
        - stage: Unit tests
          name: Release 1
          script: ./gradlew -p app/src/androidTest/java/de/test/antennapod/fontStyleTest
        - stage: UI tests
          name: Release 1
          script: 
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/espresso/fontStyle
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/espresso/themeTest
            - ./gradlew -p app/src/androidTest/java/de/test/antennapod/espresso/discoveryPage
